http:
  host: 'localhost'
  port: 3000

api:
  prefix: 'api/v1'

db:
  postgres:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    name: 'postgres'
    username: 'postgres'
    password: 'admin'
    ssl: false
    logging: false
jwt:
  secret: 'YOUR_SECRET_KEY'
  expiry: '1h'
